using Pkg
using Dates

function save_observables(Method, Obs)

    filename = "example_observables_test_results-$(today())-$(gethostname()).jl"

    if !isfile(filename)
        println("Saving new reference values in for tests in $filename")
        open(filename, "w") do io
            println(io, "# PLEASE REFORMAT THIS AUTOGENERATED FILE.")
            println(io, "# Generated on $(today())")
            println(io, "# on machine named $(gethostname())")
            commit_hash = read(`git rev-parse HEAD`, String)
            println(io, "# with code version: $commit_hash")
            println(io, "project = $(Pkg.project())")
            println(io, "dependencies = $(Pkg.dependencies())")
            println(io, "# Values generated in tests will be saved below")
            println(io, "# This preamble WILL NOT BE REGENERATED")
            println(io, "# if this file exists.")
        end

    end
    open(filename, "a") do io
        println(io, "function example_Obs(::$Method)")
        println(io, Obs)
        println(io, "end")
    end
end
