using Pkg
using Dates

function save_observables(Method, Obs)

    filename = "example_observables_test_results-$(today())-$(gethostname()).jl"

    if !isfile(filename)
        println("Saving new reference values in for tests in $filename")
        commit_hash = read(`git rev-parse HEAD`, String)
        open(filename, "w") do io
            println(
                io,
                """
# PLEASE REFORMAT THIS AUTOGENERATED FILE.
# Generated on $(today())
# on machine named $(gethostname())
# with code version: $commit_hash
using Pkg
""",
            )
            println(io, "project = $(Pkg.project())")
            println(io, "dependencies = $(Pkg.dependencies())")
            println(
                io,
                """
# Values generated in tests will be saved below
# This preamble WILL NOT BE REGENERATED")
# if this file exists.
""",
            )
        end

    end
    open(filename, "a") do io
        println(io, "function example_Obs(::$(typeof(Method)))")
        println(io, Obs)
        println(io, "end")
    end
end
