name: CI

on:
  push:
    branches: [ "master", "CI" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: julia:latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          julia --threads=4 -e 'using Pkg                                                   
                                Pkg.activate(".")
                                Pkg.add(url="https://github.com/NilsNiggemann/SpinFRGLattices.jl")
                                Pkg.test()'

      - name: Format Check
        run: |
          julia -e 'using Pkg
                    Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter 
                    @assert format(".") "Code not properly formatted!"'
