name: Run tests

on: 
  push:
    branches:
      - master
      - CI-LFS
  pull_request:
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      - name: Install dependencies and Test
        run: |
          julia --threads=4 -e 'using Pkg                                                   
                                Pkg.activate(".")
                                Pkg.add(url="https://github.com/NilsNiggemann/SpinFRGLattices.jl")
                                Pkg.test()'
