name: Run tests

on: 
  push:
    branches:
      - master
      - CI-LFS
  pull_request:
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - uses: julia-actions/setup-julia@v1
      - name: Install dependencies and Test - PMFRGCore.jl
        run: |
          export JULIA_PKG_PRECOMPILE_AUTO=0
          julia -e 'macro pex(expr)
                        quote
                        println("Command: ", $(string(expr)))
                        $expr
                        println("Command: ", $(string(expr)), " terminated.")
                        end
                    end
                    @pex using Pkg
                    @pex Pkg.activate("./PMFRGCore.jl")
                    @pex Pkg.add(url="https://github.com/NilsNiggemann/SpinFRGLattices.jl")
                    @pex ENV["JULIA_PKG_PRECOMPILE_AUTO"]=1
                    @pex Pkg.test()'
      - name: Install dependencies and Test - PMFRGSolve.jl
        run: |
          export JULIA_PKG_PRECOMPILE_AUTO=0
          julia -e 'macro pex(expr)
                        quote
                        println("Command: ", $(string(expr)))
                        $expr
                        println("Command: ", $(string(expr)), " terminated.")
                        end
                    end
                    @pex using Pkg
                    @pex Pkg.activate("./PMFRGSolve.jl")
                    @pex Pkg.develop([(;url="https://github.com/NilsNiggemann/SpinFRGLattices.jl"),
                                      (;path="./PMFRGCore.jl")])
                    @pex ENV["JULIA_PKG_PRECOMPILE_AUTO"]=1
                    @pex Pkg.test()'
      - name: Install dependencies and Test - PMFRG.jl
        run: |
          export JULIA_PKG_PRECOMPILE_AUTO=0
          julia -e 'macro pex(expr)
                        quote
                        println("Command: ", $(string(expr)))
                        $expr
                        println("Command: ", $(string(expr)), " terminated.")
                        end
                    end
                    @pex using Pkg
                    @pex Pkg.activate(".")
                    @pex Pkg.develop([(;url="https://github.com/NilsNiggemann/SpinFRGLattices.jl"),
                                      (;path="./PMFRGSolve.jl"),
                                      (;path="./PMFRGCore.jl")])
                    @pex ENV["JULIA_PKG_PRECOMPILE_AUTO"]=1
                    @pex Pkg.test()'
      - name: Formatting Check
        run: |
          julia -e 'using Pkg
                    Pkg.add("JuliaFormatter")'
          julia -e 'using JuliaFormatter 
                    @assert format(".") "Code not properly formatted!"'
